#!/bin/sh

set -e

[ -f /etc/default/datavision-server ] && . /etc/default/datavision-server

IS_UPGRADE=false


case "$1" in
	configure)
	[ -z "$GRAFANA_USER" ] && GRAFANA_USER="grafana"
	[ -z "$GRAFANA_GROUP" ] && GRAFANA_GROUP="grafana"
	if ! getent group "$GRAFANA_GROUP" > /dev/null 2>&1 ; then
	    addgroup --system "$GRAFANA_GROUP" --quiet
	fi
	if ! id $GRAFANA_USER > /dev/null 2>&1 ; then
	    adduser --system --home /usr/share/grafana --no-create-home \
		--ingroup "$GRAFANA_GROUP" --disabled-password --shell /bin/false \
		"$GRAFANA_USER"
	fi

	# Set user permissions on /var/log/grafana, /var/lib/grafana
	mkdir -p /var/log/grafana /var/lib/grafana
	chown -R $GRAFANA_USER:$GRAFANA_GROUP /var/log/grafana /var/lib/grafana
	chmod 755 /var/log/grafana /var/lib/grafana

  # copy user config files
  if [ ! -f $CONF_FILE ]; then
    cp /usr/share/grafana/conf/sample.ini $CONF_FILE
    cp /usr/share/grafana/conf/ldap.toml /etc/grafana/ldap.toml
  fi

  if [ ! -f $PROVISIONING_CFG_DIR ]; then
    mkdir -p $PROVISIONING_CFG_DIR/dashboards $PROVISIONING_CFG_DIR/datasources
    cp /usr/share/grafana/conf/provisioning/dashboards/sample.yaml $PROVISIONING_CFG_DIR/dashboards/sample.yaml
    cp /usr/share/grafana/conf/provisioning/datasources/sample.yaml $PROVISIONING_CFG_DIR/datasources/sample.yaml
  fi

	# configuration files should not be modifiable by grafana user, as this can be a security issue
	chown -Rh root:$GRAFANA_GROUP /etc/grafana/*
	chmod 755 /etc/grafana
	find /etc/grafana -type f -exec chmod 640 {} ';'
	find /etc/grafana -type d -exec chmod 755 {} ';'

  # If $1=configure and $2 is set, this is an upgrade
  if [ "$2" != "" ]; then
    IS_UPGRADE=true
  fi

  if [ "x$IS_UPGRADE" != "xtrue" ]; then
    if command -v systemctl >/dev/null; then
      echo "### NOT starting on installation, please execute the following statements to configure grafana to start automatically using systemd"
      echo " sudo /bin/systemctl daemon-reload"
      echo " sudo /bin/systemctl enable datavision-server"
      echo "### You can start datavision-server by executing"
      echo " sudo /bin/systemctl start datavision-server"
    elif command -v update-rc.d >/dev/null; then
      echo "### NOT starting datavision-server by default on bootup, please execute"
      echo " sudo update-rc.d datavision-server defaults 95 10"
      echo "### In order to start datavision-server, execute"
      echo " sudo service datavision-server start"
    fi
  elif [ "$RESTART_ON_UPGRADE" = "true" ]; then

    echo -n "Restarting datavision-server service..."

    if command -v systemctl >/dev/null; then
      systemctl daemon-reload
      systemctl restart datavision-server || true
    elif [ -x /etc/init.d/datavision-server ]; then
      if command -v invoke-rc.d >/dev/null; then
        invoke-rc.d datavision-server restart || true
      else
        /etc/init.d/datavision-server restart || true
      fi
    fi
    echo " OK"

	fi
	;;
esac
